# Missing values
```{r, echo=FALSE}
library(knitr)
library(ggplot2)
setwd("~/Desktop")
NYC <- read.csv("NYC.csv")
```
We first check if there are any NA values in the dataset:
```{r}
any(is.na(NYC))
```
However, after closer inspection, we saw that there are entries labeled with "No Data". Thus, we need to treat those entries as NAs.
```{r}
NYC_na <- NYC %>%
  na_if("No Data")
any(is.na(NYC_na))
sum(is.na(NYC_na))/prod(dim(NYC_na))*100 #in percentage
```
## Missing Pattern plot
```{r}
missing_plot <- function(data, display = "counts"){
  #missing pattern
  missing_patterns <- data.frame(is.na(data)) %>%
    group_by_all() %>%
    count(name = "count", sort = TRUE) %>%
    ungroup()
  
  key_order <- sort(colSums(data.frame(is.na(data))), decreasing = T)
  key_missing <- rep(key_order, each = nrow(missing_patterns))
  if(display == "counts"){
    #top plot
    up <- key_order %>%
      as.data.frame() %>%
      rownames_to_column("variable") %>%
      ggplot(mapping = aes(x = reorder(variable, desc(.)), y = .))+
      geom_bar(stat = "identity") +
      xlab("") + ylab("count") +
      theme(axis.text.x = element_text(angle = -45, hjust = 0))
    #right plot
    right <- missing_patterns %>%
      rownames_to_column("pattern") %>%
      ggplot(mapping = aes(x = count, y = reorder(pattern, desc(as.numeric(pattern))))) +
      geom_bar(stat = "identity") +
      xlab("row count") + ylab("")
  }
  else if(display == "percent"){
    #top plot
    up <- key_order %>%
      as.data.frame() %>%
      mutate(percentage = ./nrow(data)*100) %>%
      rownames_to_column("variable") %>%
      ggplot(mapping = aes(x = reorder(variable, desc(percentage)), y = percentage))+
      geom_bar(stat = "identity") +
      xlab("") + ylab("% rows missing") +
      ylim(0, 100) +
      theme(axis.text.x = element_text(angle = -45, hjust = 0))
    #right plot
    right <- missing_patterns %>%
      mutate(percentage = count/nrow(data)*100) %>%
      rownames_to_column("pattern") %>%
      ggplot(mapping = aes(x = percentage, y = reorder(pattern, desc(as.numeric(pattern))))) +
      geom_bar(stat = "identity") +
      xlab("%rows") + ylab("") +
      xlim(0, 100)
  }
  
  #identify complete case
  row <- rowSums(missing_patterns[-ncol(missing_patterns)])
  comp_ind <- which(row == 0)
  
  #initialize fill/alpha vector
  fill_alpha <- rep(0.5, nrow(missing_patterns))
  fill_alpha[comp_ind] <- 1
  
  #main plot
  main <- missing_patterns %>% 
    select(-count) %>%
    select(names(key_missing)) %>%
    rownames_to_column("pattern") %>%
    gather(key, value, -pattern) %>%
    mutate(missing = ifelse(value == 0, F, T)) %>%
    cbind(key_missing) %>%
    ggplot(mapping = aes(x = reorder(key, desc(key_missing)), 
                         y = reorder(pattern, desc(as.numeric(pattern))), 
                         fill = missing)) +
    geom_tile(color = "white", show.legend = F, aes(alpha = pattern)) +
    xlab("variable") + ylab("missing pattern") +
    scale_fill_manual(values = c("gray", "purple")) +
    scale_alpha_manual(values = fill_alpha) +
    geom_text(aes(x = names(key_order)[length(key_order)/2+1], 
                  y = as.character(comp_ind), label = "complete cases")) +
    theme(axis.text.x = element_text(angle = -45, hjust = 0))
  
  layout <- "
  BBB##
  AAAC#
  AAAC#
  AAAC#
  "
  main + up + right + plot_layout(design = layout)
}
```