# Interactive component

<iframe src="section6.html" width="900" height="1000"></iframe>

The inspiration of the interactive plot comes from AnneThor's `treemap` repository on Github. For further reference, please visit the link https://github.com/AnneThor/treemap 

100 schools that are identified as richest, based on the proportion of poverty from 2017-2018 academic year, were selected for this interactive visualization. This interactive plot is a comprehensive description of the top 100 richest schools in New York City. If you hover the cursor over the box representing a school, you will be able to see the full name of the school, and the number of students who were enrolled in the 2017-2018 academic year. We believe that this interactive plot can give more direct understanding about the school information, the student's economic status, as well as geographical information about the school, which can consolidate your understanding about the entire project after seeing the analysis and visualizations from previous chapters.