--- 
title: "NYC School Snapshot"
author: "Pinyi Yang & Yuan Heng"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
Inequality, including racial, gender, disabilities, has always been a public problem, particularly in schools. In the past few years, there has been multiple incidents relating ethnicity inequalities. For example, George Floyd's tragedy led to a wave of "[Black Lives Matter](https://www.cbsnews.com/news/george-floyd-black-lives-matter-impact/)" campaign; the death of [Chinese student at Chicago university](https://www.scmp.com/news/china/diplomacy/article/3157087/chicagos-chinese-students-fear-death-wake-fatal-shooting) revealed a series of discriminating activities against Asian international students. Similarly, gender and disability discrimination are both common problems in schools. Preventing inequalities at school is especially important because students are really vulnerable, and being harmed by inequality will leave scars in their mental wellness. Thus, we aim to gain more insights about inequalities by investigating the distribution of ethnicity, gender, disability through other indicators in schools in New York. In this way, we can determine if inequalities exist in schools, which can allow agencies to make adjustments to bring about equality among students.

Apart from academia purpose of education, making sure schools reflect the diversity of its residents is a top priority. Improving educational equity has long been a focus of the society, especially New York City, where public schools remain some of the most segregated in the country. 

> According to the New York City Council, "In New York City public schools, 74.6% of black and Hispanic students attend a school with less than 10% white students. Additionally, 34.3% of white students attend a school with more than 50% white students."

Apart from race and ethnicity, the segregation also can be found among different groups of gender, poverty and even students' disability. Severe discrepancies still exist when breaking down the huge population of students and investigating their access to education and schools. 

In our project, we try to perform exploratory analysis of demographic school data in New York City from 2013- 2018 and answer questions as follows:

* Does the composition of ethnic groups correlate with the poverty rate of the student population? Is it more likely to have a lower poverty rate when the percentage of white students is higher?

* Does the number of total enrolled students correlate with the distribution of ethnic groups? For example, a bigger school has a more even composition of different ethnic groups (i.e. similar percentage for black, Asian, and white)?

* Does the composition of different genders correlate with the school’s poverty level? Do schools that have relatively higher poverty rates have more male students?

* Does the school level(eg. Primary school, middle school, high school) or ethic groups correlates?

* Does the distribution of schools in different districts have relations towards ethnic groups, gender groups and poverty level?
